### ISSUE TITLE
unable to build lib with cmake

### ISSUE THREAD

**Issue by synthesinglegend** [orange-cpp/omath#13]
![image](https://github.com/user-attachments/assets/5dab7803-3af5-4b90-893f-e730700f3114)

**Comment by orange-cpp** [comment]
Hello! Please use x64 native tools that come with MSVC compiler 
![image](https://github.com/user-attachments/assets/021525a6-c49c-4943-bad1-6dea75de831b)
Now try to configure project again
![image](https://github.com/user-attachments/assets/7b502b48-1252-45f7-b2eb-374c10847c3d)
And also i've changed presets names so just use \<your platform\>-\<build type\> like "windows-release"
